name: vehicle-detection
channels:
    - https://conda.anaconda.org/menpo
dependencies:
    - python==3.5
    - numpy
    - matplotlib
    - scikit-learn
    - scikit-image
    - matplotlib
    - jupyter
    - opencv
    - tensorflow
    - keras
    - moviepy
    - pillow
